pipeline {
    agent any
    
    environment {
        //DOCKER_COMPOSE_FILE = 'docker-compose.yml'
        DOCKER_IMAGE_PREFIX = 'nafrin/python'
        DOCKER_REGISTRY = 'https://index.docker.io/v1/'
        //KUBE_CONFIG_PATH = 'C:/Users/MyPc/.kube/config'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/nafrinmeir/projapplied.git'
            }
        }
        stage('Build') {
            steps {
                bat '''
                cd flask_app
                docker build -t flask-app:latest .
                '''
            }
        }
        
        stage('Run') {
            steps {
                bat 'docker run -d -p 8000:8000 --name flask-application flask-app'
            }
        }
        
        stage('Test') {
            steps {
                bat 'python -m unittest discover tests'
            }
        }
        
        stage('Push Image') {
            steps {
                bat '''
                docker tag flask-app:latest nafrin/flask-app:latest
                docker push nafrin/flask-app:latest
                '''
            }
        }
        stage('Deploy') {
            steps {
                bat 'ansible-playbook ansible/playbook.yaml'
            }
        }
    }
}
